name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: Create Release
    runs-on: macos-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Xcode
      run: sudo xcode-select -s /Applications/Xcode_15.0.app
      
    - name: Build and Test
      run: |
        swift build
        swift test
        
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        
    - name: Build Documentation
      run: |
        swift package generate-documentation
        
    - name: Upload Documentation
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: .build/plugins/Swift-DocC/output/
        
    - name: Notify Release
      run: |
        echo "Release ${{ github.ref }} has been created successfully!"
        echo "Documentation has been generated and uploaded as artifacts."
